### ISSUE TITLE
define-prefix doesn't work for non-standard pkgconfig paths

### ISSUE THREAD

**Issue by lazka** [pkgconf/pkgconf#286]
**Short summary of my use case:**

* in MSYS2 we want/need to update to ffmpeg 5 while keeping 4.4 for some packages
* for this we install the .pc files into `<prefix>/lib/ffmpeg4.4/pkgconfig/` instead of `<prefix>/lib/pkgconfig/` (we just set a different `--incdir` and `--libdir` to ffmpeg configure) so we can set the alternative pc path via something like `export PKG_CONFIG_PATH="${MINGW_PREFIX}/lib/ffmpeg4.4/pkgconfig:$PKG_CONFIG_PATH"` when wanting a package to links against 4.4

**Problem:**

The define-prefix logic in pkgconf doesn't support this since it just strips "<something>/pkgconfig" from paths, so the detected prefix is

* "`<prefix>/lib`~~/ffmpeg4.4/pkgconfig~~" instead of 
* "`<prefix>`~~/lib/ffmpeg4.4/pkgconfig~~".

So we get the following wrong output (one "/lib" too much):

```console
$ export PKG_CONFIG_PATH="${MINGW_PREFIX}/lib/ffmpeg4.4/pkgconfig:$PKG_CONFIG_PATH"
$ pkgconf.exe --libs --cflags libavcodec
-IC:/msys64/ucrt64/lib/include/ffmpeg4.4 -LC:/msys64/ucrt64/lib/lib/ffmpeg4.4 -lavcodec
```

**Context / Question:**

The logic for this is defined here:

* pkgconf: https://github.com/pkgconf/pkgconf/blob/78f3abc9359cbe08258c381445b445206b2a0485/libpkgconf/pkg.c#L204

* The same logic in pkg-config: https://gitlab.freedesktop.org/pkg-config/pkg-config/-/blob/d97db4fae4c1cd099b506970b285dc2afd818ea2/parse.c#L1000

I'm not quite sure how to work around/fix that without hacks, so I'm asking here if someone had a similar problem and maybe an idea for a solution or a workaround.

The only thing I can think of is patching the .pc files after the build from `libdir=${prefix}/lib/ffmpeg4.4` to  `libdir=${prefix}/../lib/ffmpeg4.4`

If there is no solution feel free to close. At least I can link to this issue from my workarounds :)

**Comment by huyubiao** [comment]
I have the same problem with Linux.
- version：pkgconf 1.9.4

### prepare:
```
$ export LINUX_PREFIX=/usr
$ mkdir -p ${LINUX_PREFIX}/lib64/python3.7/pkgconfig
$ mv python-3.7.pc  ${LINUX_PREFIX}/lib64/python3.7/pkgconfig
$ export PKG_CONFIG_PATH="${LINUX_PREFIX}/lib64/python3.7/pkgconfig:$PKG_CONFIG_PATH"
$ pkgconf --define-prefix --libs --cflags python-3.7
```

### python-3.7.pc:
```
# See: man pkg-config
prefix=/usr
exec_prefix=/usr
libdir=${prefix}/lib64
includedir=${prefix}/include

Name: Python
Description: Python library
Requires:
Version: 3.7
Libs.private: -lcrypt -lpthread -ldl  -lutil
Libs: -L${libdir} -lpython3.7m
Cflags: -I${includedir}/python3.7m
```

### output:
```
$ -I/usr/lib64/include/python3.7m -L/usr/lib64/lib64 -lpython3.7m
```

I created an additional `/python3.7/pkgconfig` in `/usr/lib64` to store python-3.7.pc,It comes with extra /lib64.
I review the code and only parsed the last two levels of directories. I don't know if this is a bug?

**Comment by kaniini** [comment]
I think this is fixed, because I can't reproduce it.

```
~/pkgconf $ cat tests/lib1/child-prefix/pkgconfig/child-prefix-1.pc 
prefix=/usr
exec_prefix=/usr
libdir=${prefix}/lib64
includedir=${prefix}/include

Name: child-prefix-1
Description: child prefix 1 test data
Requires:
Version: 1.0
Libs: -L${libdir} -lchild-prefix-1
Cflags: -I${includedir}/child-prefix-1
~/pkgconf $ ./pkgconf --with-path=/home/kaniini/pkgconf/tests/lib1/child-prefix/pkgconfig --define-prefix --cflags --libs child-prefix-1
-I/home/kaniini/pkgconf/tests/lib1/include/child-prefix-1 -L/home/kaniini/pkgconf/tests/lib1/lib64 -lchild-prefix-1
```

I will add a regression test though...

**Comment by lazka** [comment]
huh, determine_prefix() logic hasn't changed in 7 years, so I wonder how. I'll test again.

**Comment by lazka** [comment]
It's all still the same, also visible in the example above, the detected prefix is `/home/kaniini/pkgconf/tests/lib1` while the real one is  `/home/kaniini/pkgconf/tests`
